language: node_js
node_js:
    - "8"
    - "10"

services:
    - postgresql

before_script:
    - psql -c 'create database maildb;' -U postgres

script:
    - npm run lint
    - npm test

after_success:

# enable codecov, which doesn't currently work for plugins because
# plugins are run in vm.runInNewContext()
#
#   - npm install istanbul codecov
#   - npm run cover
#   - ./node_modules/.bin/codecov

sudo: false
